### ISSUE TITLE
Uncaught TypeError: Cannot read property '10' of undefined

### ISSUE THREAD

**Issue by meta-riddhi-jain** [carlosbaraza/yard#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '10' of undefined

```
At C:\Users\Riddhi\AppData\Local\atom\app-1.19.3\resources\app\node_modules\text-buffer\lib\text-buffer.js:899

TypeError: Cannot read property '10' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/text-buffer/lib/text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.19.3/resources/app/src/text-editor.js:1673:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.3/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.3/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:41 yard:create (input.hidden-input)
     -3:39.4.0 editor:consolidate-selections (input.hidden-input)
     -3:39.4.0 core:cancel (input.hidden-input)
     -3:37.9.0 editor:newline (input.hidden-input)
     -3:37.3.0 core:save (input.hidden-input)
  3x -3:17.8.0 core:undo (input.hidden-input)
  3x -3:17 core:save (input.hidden-input)
  2x -3:16.3.0 core:undo (input.hidden-input)
  2x -3:15.8.0 core:save (input.hidden-input)
     -2:53.2.0 yard:create (span.syntax--entity.syntax--name.syntax--function.syntax--ruby)
 14x -2:49.9.0 core:move-left (input.hidden-input)
     -2:47.7.0 editor:newline (input.hidden-input)
     -2:40.9.0 yard:create (input.hidden-input)
     -1:19.4.0 settings-view:open (input.hidden-input)
     -0:37.6.0 core:confirm (input.hidden-input)
     -0:09.2.0 yard:create (span.syntax--entity.syntax--name.syntax--function.syntax--ruby)
```

### Non-Core Packages

```
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
