### ISSUE TITLE
Uncaught TypeError: Cannot read property '32' of undefined

### ISSUE THREAD

**Issue by mityakoval** [carlosbaraza/yard#11]
Steps to reproduce:

1. Navigate to `def` keyword
2. Press `cmd + Enter`

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '32' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899

TypeError: Cannot read property '32' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:46.2.0 yard:create (input.hidden-input)
     -0:12.3.0 core:close (input.hidden-input)
     -0:07.2.0 core:save (div.tool-panel.tree-view)
     -0:03.6.0 core:move-right (input.hidden-input)
     -0:03.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:01.7.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.4 
atom-css-comb 3.3.1 
atom-everydayrails-rspec 0.4.0 
busy-signal 1.4.3 
cucumber 0.6.0 
cucumber-step 0.2.0 
dash 1.7.1 
emmet 2.4.3 
file-icons 2.1.10 
intentions 1.1.5 
language-haml 0.25.0 
language-rspec 0.6.3 
linter 2.2.0 
linter-haml 2.0.1 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.4 
minimap 4.29.6 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
rails-snippets 2.16.0 
rspec 0.3.4 
ruby-test 1.0.2 
Sublime-Style-Column-Selection 1.7.4 
todo-show 1.11.0 
toggle-quotes 1.0.1 
uglify 1.3.1 
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
