### ISSUE TITLE
Uncaught TypeError: Cannot read property '22' of undefined

### ISSUE THREAD

**Issue by kieranklaassen** [carlosbaraza/yard#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '22' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property '22' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:33:33)
    at /packages/yard/lib/yard.coffee:23:30
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at Object.create (/packages/yard/lib/yard.coffee:20:21)
    at /packages/yard/lib/yard.coffee:12:24)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:44.2.0 core:backspace (input.hidden-input)
     -0:43.9.0 core:move-up (input.hidden-input)
  2x -0:43.5.0 core:move-right (input.hidden-input)
     -0:42.8.0 editor:select-to-end-of-line (input.hidden-input)
     -0:42.5.0 core:backspace (input.hidden-input)
  2x -0:42 core:move-down (input.hidden-input)
     -0:41.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:36.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:32.1.0 core:backspace (input.hidden-input)
     -0:28.3.0 core:copy (input.hidden-input)
  2x -0:27.8.0 core:backspace (input.hidden-input)
     -0:27.1.0 core:move-up (input.hidden-input)
  3x -0:26.8.0 core:backspace (input.hidden-input)
     -0:19.1.0 command-palette:toggle (input.hidden-input)
     -0:17.5.0 core:confirm (input.hidden-input)
     -0:17.5.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
aligner-scss 1.3.1 
angularjs 0.4.0 
atom-beautify 0.30.5 
busy-signal 1.4.3 
capybara-snippets 0.2.0 
coffee-paste 0.8.0 
color-picker 2.2.5 
comment-headers 2.15.0 
coverage 0.6.1 
dash 1.7.1 
file-icons 2.1.12 
gemsource 0.3.0 
git-plus 7.9.3 
grammar-mode 1.1.0 
highlight-selected 0.13.1 
html2haml 0.10.0 
img-placeholder 2.0.1 
intentions 1.1.5 
kite 0.48.0 
language-coffee-script-angular 2.2.0 
language-haml 0.25.2 
language-rspec-plus 0.1.1 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-haml 2.0.2 
linter-reek 2.2.2 
linter-rubocop 2.2.0 
linter-ruby 1.2.6 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
markdown-assistant 0.2.0 
markdown-preview-opener 0.1.1 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.5 
meteor-api 2.20.0 
meteor-assist 0.3.0 
meteor-helper 0.29.0 
meteor-snippets 0.5.0 
minimap 4.29.7 
minimap-color-highlight 4.1.4 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
multi-cursor 2.1.5 
pigments 0.40.2 
rails-i18n 0.1.3 
rails-i18n-autocomplete 0.4.0 
rails-partials 0.9.2 
rails-rspec 0.3.2 
rails-snippets 2.16.0 
rails-transporter 1.7.1 
railscast-theme 0.4.0 
remote-atom 1.3.11 
rspec 0.4.0 
sort-lines 0.15.0 
Termrk 1.0.0 
tidy-markdown 3.0.1 
toggle-markdown-task 0.6.0 
tool-bar-markdown-writer 0.3.0 
webbox-color 0.5.9 
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
