### ISSUE TITLE
Uncaught TypeError: Cannot read property '65' of undefined

### ISSUE THREAD

**Issue by victormartins** [carlosbaraza/yard#15]
[Enter steps to reproduce:]

1. Add the cursor inside a method
2. Executed the `Yard:Create` command.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '65' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property '65' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:33.5.0 editor:consolidate-selections (input.hidden-input)
     -0:33.5.0 core:cancel (input.hidden-input)
     -0:33 command-palette:toggle (input.hidden-input)
  3x -0:28.7.0 core:backspace (input.hidden-input)
     -0:26.2.0 core:confirm (input.hidden-input)
     -0:26.2.0 yard:create (input.hidden-input)
     -0:24.8.0 core:move-down (input.hidden-input)
     -0:23.7.0 command-palette:toggle (input.hidden-input)
     -0:21.2.0 core:confirm (input.hidden-input)
     -0:21.2.0 yard:create (input.hidden-input)
 19x -0:20.2.0 core:move-right (input.hidden-input)
  3x -0:18.2.0 core:move-down (input.hidden-input)
     -0:16.5.0 core:move-right (input.hidden-input)
     -0:08.3.0 command-palette:toggle (input.hidden-input)
     -0:05.5.0 core:confirm (input.hidden-input)
     -0:05.5.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
atom-beautify 0.30.5 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.5 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
cake-syntax 1.0.2 
change-case 0.6.5 
docblockr 0.11.0 
export-html 3.1.0 
firewatch-syntax 1.1.1 
genesis-ui 0.5.0 
git-time-machine 1.5.9 
intentions 1.1.5 
language-babel 2.75.1 
language-docker 1.1.8 
lawmaker-syntax 0.2.0 
linter 2.2.0 
linter-rubocop 2.2.0 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
paner 1.0.0 
print-atom 0.1.1 
react-snippets 1.0.0 
rspec 0.4.0 
rubocop-auto-correct 1.5.1 
ruby-block-converter 4.0.1 
ruby-syntax-replacer 0.5.1 
seti-syntax 1.1.3 
seti-ui 1.9.0 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.3 
tango-syntax 0.5.0 
todo-show 2.1.0 
toggle-quotes 1.0.1 
vim-mode 0.66.0 
yard 0.3.1 
Zen 0.18.0 
```

**Comment by nimylian** [comment]
Fixed in current release

**Comment by victormartins** [comment]
Thank you @nimylian
