### ISSUE TITLE
Uncaught TypeError: Cannot read property '31' of undefined

### ISSUE THREAD

**Issue by caomania** [carlosbaraza/yard#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '31' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property '31' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:45.4.0 yard:create (input.hidden-input)
     -0:44.2.0 editor:consolidate-selections (input.hidden-input)
     -0:44.2.0 core:cancel (input.hidden-input)
  3x -0:42.5.0 core:move-down (input.hidden-input)
  3x -0:41.3.0 core:move-up (input.hidden-input)
     -0:40.6.0 core:move-right (input.hidden-input)
     -0:39.9.0 pane:move-item-right (input.hidden-input)
     -0:39.2.0 editor:select-to-end-of-line (input.hidden-input)
     -0:38.4.0 intentions:show (input.hidden-input)
     -0:37.6.0 core:move-left (input.hidden-input)
     -0:12 intentions:show (input.hidden-input)
     -0:11.4.0 core:move-down (input.hidden-input)
     -0:11.1.0 intentions:show (input.hidden-input)
     -0:10.3.0 editor:newline-below (input.hidden-input)
     -0:09.4.0 core:undo (input.hidden-input)
     -0:08.3.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-monokai 0.10.9 
atom-monokai-soda 3.0.1 
atom-runner 2.7.1 
busy-signal 1.4.3 
intentions 1.1.5 
language-rspec 0.7.0 
linter 2.2.0 
linter-rubocop 2.2.0 
linter-ui-default 1.6.10 
open-gitup 0.0.8 
Sublime-Style-Column-Selection 1.7.4 
yard 0.3.1 
```

**Comment by caomania** [comment]
Resolved by https://github.com/carlosbaraza/yard/pull/12
