### ISSUE TITLE
Uncaught TypeError: Cannot read property '24' of undefined

### ISSUE THREAD

**Issue by jorgefuertes** [carlosbaraza/yard#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '24' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property '24' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1687:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
 25x -0:46.7.0 intentions:show (input.hidden-input)
  4x -0:38.5.0 core:backspace (input.hidden-input)
     -0:36.9.0 core:save (input.hidden-input)
     -0:35.5.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -0:34.7.0 core:confirm (input.hidden-input)
     -0:33.5.0 intentions:highlight (input.hidden-input)
     -0:33.3.0 editor:newline (input.hidden-input)
     -0:31.9.0 core:undo (input.hidden-input)
  3x -0:27.6.0 core:backspace (input.hidden-input)
  6x -0:26.2.0 core:move-right (input.hidden-input)
  6x -0:25.1.0 core:backspace (input.hidden-input)
  2x -0:16.3.0 core:move-down (input.hidden-input)
     -0:15.8.0 core:save (input.hidden-input)
     -0:14.3.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -0:13.8.0 core:confirm (input.hidden-input)
     -0:11.6.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-icons 0.2.2 
atom-soda-dark-ui 1.1.0 
atom-solarized-dark-ui 0.28.1 
atom-sync 0.7.3 
auto-indent 0.5.0 
auto-reveal-in-sidebar 0.8.0 
autocomplete-ruby 0.2.8 
autocomplete-sass 0.1.0 
busy-signal 1.4.3 
calculator 0.1.0 
color-picker 2.2.5 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
enhanced-tabs 1.7.0 
highlight-column 0.5.4 
intentions 1.1.5 
language-vue 0.23.1 
lint 0.0.1 
linter 2.2.0 
linter-coffeescript 1.0.0 
linter-rubocop 2.2.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
lorem 1.3.0 
make-coffee 0.1.1 
markdown-preview-plus 2.4.16 
multi-cursor 2.1.5 
pigments 0.40.2 
project-manager 3.3.5 
ruby-slim 0.2.0 
ruby-syntax-replacer 0.5.1 
seti-icons 1.5.4 
sinatra-snippets 1.4.0 
slim-language 2.2.0 
solarized-dark-ui 0.3.2 
sync-settings 0.8.3 
text-manipulation 0.6.0 
time-status 1.1.2 
yard 0.3.1 
zentabs 0.8.9 
```

**Comment by nimylian** [comment]
Fixed in current release
