### ISSUE TITLE
Uncaught TypeError: Cannot read property '14' of undefined

### ISSUE THREAD

**Issue by boguth** [carlosbaraza/yard#18]
[Enter steps to reproduce:]

1. Click on packages in the toolbar.
2. Click on yard
3. Click on Create Yard

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '14' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property '14' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1687:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1382:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:28.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -8:28.5.0 pane:show-item-1 (atom-pane.pane.active)
  2x -7:33.8.0 intentions:highlight (input.hidden-input)
     -7:31.3.0 core:undo (input.hidden-input)
     -7:29 core:save (input.hidden-input)
     -7:23.6.0 window:toggle-dev-tools (input.hidden-input)
  3x -4:17.1.0 core:save (input.hidden-input)
     -3:55.7.0 window:toggle-dev-tools (input.hidden-input)
     -2:20.6.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  7x -2:10.6.0 core:close (input.hidden-input)
  2x -1:57.4.0 core:backspace (input.hidden-input)
     -0:59.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
 23x -0:57.4.0 core:backspace (input.hidden-input)
     -0:32.6.0 core:confirm (input.hidden-input)
     -0:03.5.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
aligner-scss 1.3.1 
atom-beautify 0.30.9 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
coffee-paste 0.8.0 
dash 1.7.1 
file-icons 2.1.14 
goto-definition 1.3.4 
highlight-selected 0.13.1 
html2haml 0.10.0 
intentions 1.1.5 
language-coffee-script-angular 2.2.0 
language-haml 0.25.2 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-haml 2.0.2 
linter-reek 2.2.2 
linter-rubocop 2.2.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
my-theme-syntax 0.0.0 
package-list 0.1.2 
rails-rspec 0.3.2 
sort-lines 0.18.0 
teletype 0.2.3 
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
