### ISSUE TITLE
Uncaught TypeError: Cannot read property '21' of undefined

### ISSUE THREAD

**Issue by boguth** [carlosbaraza/yard#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '21' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Cannot read property '21' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1687:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:15.1.0 core:close (input.hidden-input)
     -2:13.5.0 core:save (input.hidden-input)
     -2:05.8.0 editor:newline (input.hidden-input)
     -2:05.5.0 core:move-up (input.hidden-input)
  3x -2:02.3.0 core:backspace (input.hidden-input)
     -2:00.3.0 autocomplete-plus:confirm (input.hidden-input)
  5x -1:58.6.0 core:backspace (input.hidden-input)
  2x -1:56.7.0 core:save (input.hidden-input)
     -1:50.5.0 core:backspace (input.hidden-input)
  5x -1:49.9.0 core:save (input.hidden-input)
     -0:10.4.0 command-palette:toggle (input.hidden-input)
     -0:06.5.0 core:confirm (input.hidden-input)
     -0:06.5.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
aligner-scss 1.3.1 
atom-beautify 0.30.9 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
coffee-paste 0.8.0 
dash 1.7.1 
file-icons 2.1.14 
goto-definition 1.3.4 
highlight-selected 0.13.1 
html2haml 0.10.0 
intentions 1.1.5 
language-coffee-script-angular 2.2.0 
language-haml 0.25.2 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-haml 2.0.2 
linter-reek 2.2.2 
linter-rubocop 2.2.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
my-theme-syntax 0.0.0 
package-list 0.1.2 
rails-rspec 0.3.2 
sort-lines 0.18.0 
teletype 0.2.3 
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
