### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

### ISSUE THREAD

**Issue by AlexWayfer** [carlosbaraza/yard#6]
[Enter steps to reproduce:]

1. Open panel of [advanced-open-file](https://atom.io/packages/advanced-open-file) by `Ctrl+Alt+O`
2. `Ctrl+V` some existing path
3. Fast type `Enter`

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: linux 4.11.6-3-ARCH
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

```
At /home/alex/.atom/packages/yard/lib/yard.coffee:10

TypeError: Cannot read property 'getLastCursor' of undefined
    at Object.create (/packages/yard/lib/yard.coffee:10:20)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:56.4.0 intentions:highlight (input.hidden-input)
     -0:56.3.0 core:save (input.hidden-input)
     -0:49.3.0 intentions:highlight (input.hidden-input)
     -0:49.1.0 core:save (input.hidden-input)
     -0:43 intentions:highlight (input.hidden-input)
     -0:43 core:save (input.hidden-input)
     -0:34.3.0 intentions:highlight (input.hidden-input)
     -0:34 settings-view:open (input.hidden-input)
     -0:29.4.0 core:confirm (input.hidden-input)
     -0:21.5.0 core:close (div.package-detail.panels-item)
     -0:15.5.0 intentions:highlight (input.hidden-input)
     -0:15.3.0 core:close (input.hidden-input)
     -0:07.6.0 advanced-open-file:toggle (atom-pane.pane)
     -0:07.3.0 core:paste (input.hidden-input)
     -0:07.1.0 yard:create (input.hidden-input)
     -0:05.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.3 
atom-material-syntax 1.0.6 
atom-smart-tabs 0.1.0 
atom-typescript 11.0.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-paths 1.0.5 
autocomplete-ruby 0.2.8 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
color-picker 2.2.5 
crystal 0.2.1 
editorconfig 2.2.2 
genesis-ui 0.5.0 
git-time-machine 1.5.9 
goto-definition 1.3.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-crystal-actual 0.35.0 
language-fish-shell 1.0.5 
language-haml 0.24.5 
language-vue 0.23.0 
linter 2.2.0 
linter-erb 1.1.0 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-jshint 3.1.4 
linter-markdown 4.0.1 
linter-reek 2.2.1 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-spell 0.14.0 
linter-stylelint 3.10.0 
linter-ui-default 1.6.2 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
monocolor-blue-syntax 1.0.0 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
northem-atom-syntax 2.1.0 
northem-dark-atom-syntax 2.1.0 
nucleus-dark-ui 0.12.3 
remember-file-positions 0.2.3 
revert-buffer 0.5.0 
ruby-block 0.3.6 
ruby-define-method 0.2.2 
seti-icons 1.5.4 
seti-ui 1.8.0 
single-click-open 0.2.2 
space-tab 0.4.2 
space-underscore 0.1.1 
split-diff 1.4.3 
symbols-tree-view 0.14.0 
sync-settings 0.8.2 
synced-sidebar 0.4.3 
tab-control 0.6.10 
tabs-to-spaces 1.0.3 
tasks 2.6.6 
toggle-quotes 1.0.1 
tree-view-open-files 0.3.0 
yard 0.3.1 
zentabs 0.8.8 
```

**Comment by nimylian** [comment]
@AlexWayfer is this still an issue in the current version?

**Comment by AlexWayfer** [comment]
> @AlexWayfer is this still an issue in the current version?

I stopped using `advanced-open-file`, but I can check it, if you want.

**Comment by AlexWayfer** [comment]
With `yard 0.5.0` and Atom `1.23.0` I don't see any errors on these steps.

Thank you :man_shrugging:
