### ISSUE TITLE
Uncaught TypeError: Cannot read property '17' of undefined

### ISSUE THREAD

**Issue by envygeeks** [carlosbaraza/yard#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.2
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '17' of undefined

```
At /usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/text-buffer.js:912

TypeError: Cannot read property '17' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/text-buffer.js:907:24)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom-beta/resources/app/src/text-editor.js:1672:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom-beta/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/usr/share/atom-beta/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/usr/share/atom-beta/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/usr/share/atom-beta/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom-beta/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  5x -0:23.4.0 core:move-down (input.hidden-input)
     -0:22.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:22.2.0 editor:newline (input.hidden-input)
     -0:21 core:backspace (input.hidden-input)
     -0:20.8.0 editor:newline (input.hidden-input)
     -0:20.4.0 intentions:highlight (input.hidden-input)
     -0:20.2.0 command-palette:toggle (input.hidden-input)
     -0:18.2.0 core:confirm (input.hidden-input)
     -0:18.2.0 yard:create (input.hidden-input)
  7x -0:08.6.0 core:backspace (input.hidden-input)
  3x -0:06.5.0 core:move-down (input.hidden-input)
     -0:05.2.0 core:move-up (input.hidden-input)
     -0:04.8.0 intentions:highlight (input.hidden-input)
     -0:04.1.0 command-palette:toggle (input.hidden-input)
     -0:03.1.0 core:confirm (input.hidden-input)
     -0:03.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.2 
keyboard-sounds 0.2.0 
language-docker 1.1.8 
language-liquid 0.6.0 
linter 2.2.0 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
travis-ci-status 1.3.1 
uuidgen 1.2.1 
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
