### ISSUE TITLE
Uncaught TypeError: Cannot read property '19' of undefined

### ISSUE THREAD

**Issue by Gnirt** [carlosbaraza/yard#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '19' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:904

TypeError: Cannot read property '19' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:58.6.0 core:select-up (input.hidden-input)
  2x -1:58 core:copy (input.hidden-input)
     -1:57.4.0 pane:show-previous-item (input.hidden-input)
     -1:56.5.0 core:paste (input.hidden-input)
     -1:55.4.0 pane:show-next-item (input.hidden-input)
     -1:54.8.0 pane:show-previous-item (input.hidden-input)
     -1:54.3.0 pane:show-next-item (input.hidden-input)
     -1:52.1.0 tree-view:reveal-active-file (input.hidden-input)
     -1:51.6.0 core:move-up (div.tool-panel.tree-view)
     -1:51.3.0 tree-view:open-selected-entry (div.tool-panel.tree-view)
     -1:12 editor:newline-below (input.hidden-input)
  2x -1:11.1.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:37.9.0 core:move-down (input.hidden-input)
     -0:36.4.0 pane:show-next-item (input.hidden-input)
     -0:21.8.0 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-railscast-theme.theme-atom-dark-ui)
     -0:10.2.0 yard:create (div.line.cursor-line)
```

### Non-Core Packages

```
railscast-theme 0.3.0 
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
