### ISSUE TITLE
Uncaught TypeError: Cannot read property '133' of undefined

### ISSUE THREAD

**Issue by larryzhao** [carlosbaraza/yard#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [yard](https://github.com/carlosbaraza/yard) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property '133' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899

TypeError: Cannot read property '133' of undefined
    at Object.findStartRow (/packages/yard/lib/yard.coffee:19:32)
    at /packages/yard/lib/yard.coffee:12:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at Object.create (/packages/yard/lib/yard.coffee:11:12)
    at /packages/yard/lib/yard.coffee:6:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:40 vim-mode-plus:reset-normal-mode (input.hidden-input)
  3x -0:39.7.0 vim-mode-plus:move-up (input.hidden-input)
  4x -0:38.9.0 vim-mode-plus:move-down (input.hidden-input)
  6x -0:37.8.0 vim-mode-plus:move-up (input.hidden-input)
     -0:36.3.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -0:36 vim-mode-plus:move-down (input.hidden-input)
     -0:34.9.0 vim-mode-plus:insert-at-first-character-of-line (input.hidden-input)
     -0:34.8.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  6x -0:34.7.0 vim-mode-plus:move-right (input.hidden-input)
  5x -0:33.8.0 vim-mode-plus:move-down (input.hidden-input)
  7x -0:32.6.0 vim-mode-plus:move-up (input.hidden-input)
     -0:31.4.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:30.6.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:30.5.0 vim-mode-plus:undo (input.hidden-input)
  8x -0:06.2.0 vim-mode-plus:move-left (input.hidden-input)
     -0:04.8.0 yard:create (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
fonts 3.0.2 
nucleus-dark-ui 0.12.3 
seti-syntax 1.1.3 
seti-ui 1.9.0 
spacegray-dark-ui 0.13.0 
vim-mode-plus 0.98.0 
yard 0.3.1 
```

**Comment by nimylian** [comment]
Fixed in current release
